init

diff --git a/service/shadowsocks-manager-debian b/service/shadowsocks-manager-debian
--- a/service/shadowsocks-manager-debian
+++ b/service/shadowsocks-manager-debian
@@ -1,39 +1,55 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ### BEGIN INIT INFO
-# Provides:          Shadowsocks
+# Provides:          shadowsocks-libev
 # Required-Start:    $network $local_fs $remote_fs
 # Required-Stop:     $network $local_fs $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Fast tunnel proxy that helps you bypass firewalls
-# Description:       Start or stop the Shadowsocks server
+# Description:       Start or Stop the shadowsocks-libev server to support multiple users with ss-manager
 ### END INIT INFO
 
-# Author: Teddysun <i@teddysun.com>
+# Author: QuNiu <https://github.com/quniu>
 
-if [ -f /usr/bin/ssserver ]; then
-    DAEMON=/usr/bin/ssserver
-elif [ -f /usr/local/bin/ssserver ]; then
-    DAEMON=/usr/local/bin/ssserver
+if [ -f /usr/local/bin/ss-server ]; then
+    DAEMON=/usr/local/bin/ss-server
+elif [ -f /usr/bin/ss-server ]; then
+    DAEMON=/usr/bin/ss-server
 fi
-if [ -f /etc/shadowsocks-manager-python/config.json ]; then
-    CONF=/etc/shadowsocks-manager-python/config.json
-elif [ -f /etc/shadowsocks.json ]; then
-    CONF=/etc/shadowsocks.json
-fi
-NAME=shadowsocks-manager-python
-SS_NAME=SS-node-python
-SS_PORT=6000
-
+NAME=shadowsocks-manager
+CONF=/etc/shadowsocks-manager/config.json
+SS_NAME=shadowsocks-manager-node
+PID_DIR=/var/run
+PID_FILE=$PID_DIR/shadowsocks-manager.pid
 RET_VAL=0
 
-check_running(){
-    PID=$(ps -ef | grep -v grep | grep -i "${DAEMON}" | awk '{print $2}')
-    if [ -n "$PID" ]; then
-        return 0
+[ -x $DAEMON ] || exit 0
+
+if [ ! -d $PID_DIR ]; then
+    mkdir -p $PID_DIR
+    if [ $? -ne 0 ]; then
+        echo "Creating PID directory $PID_DIR failed"
+        exit 1
+    fi
+fi
+
+if [ ! -f $CONF ]; then
+    echo "$NAME config file $CONF not found"
+     exit 1
+fi
+
+check_running() {
+    if [ -r $PID_FILE ]; then
+        read PID < $PID_FILE
+        if [ -d "/proc/$PID" ]; then
+            return 0
+        else
+            rm -f $PID_FILE
+            return 1
+        fi
     else
-        return 1
+        return 2
     fi
 }
 
@@ -46,33 +62,34 @@ check_manager_running(){
     fi
 }
 
-do_status(){
+do_status() {
     check_running
-    if [ $? -eq 0 ]; then
+    case $? in
+        0)
         echo "$NAME (pid $PID) is running..."
-    else
+        ;;
+        1|2)
         echo "$NAME is stopped"
         RET_VAL=1
-    fi
+        ;;
+    esac
 }
 
-
-do_start(){
-    check_running
-    if [ $? -eq 0 ]; then
+do_start() {
+    if check_running; then
         echo "$NAME (pid $PID) is already running..."
         exit 0
     else
-        $DAEMON -c $CONF -d start
-        if [ $? -eq 0 ]; then
+        $DAEMON -v -c $CONF -f $PID_FILE
+        if check_running; then
             echo "Starting $NAME success"
         else
             echo "Starting $NAME failed"
             RET_VAL=1
         fi
-        
+
         if [ $RET_VAL -eq 0 ]; then
-            screen -dmS $SS_NAME ssserver -m aes-256-cfb -p 9000 -k abc123456 --manager-address 127.0.0.1:$SS_PORT
+            screen -dmS $SS_NAME ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001
             check_manager_running
             if [ $? -eq 0 ]; then
                 echo "Starting $SS_NAME (PID $SS_PID) success"
@@ -80,20 +97,15 @@ do_start(){
                 echo "Starting $SS_NAME failed"
                 RET_VAL=1
             fi
-        fi    
+        fi  
     fi
 }
 
-do_stop(){
-    check_running
-    if [ $? -eq 0 ]; then
-        $DAEMON -c $CONF -d stop
-        if [ $? -eq 0 ]; then
-            echo "Stopping $NAME success"
-        else
-            echo "Stopping $NAME failed"
-            RET_VAL=1
-        fi
+do_stop() {
+    if check_running; then
+        kill -9 $PID
+        rm -f $PID_FILE
+        echo "Stopping $NAME success"
 
         if [ $RET_VAL -eq 0 ]; then
             check_manager_running
@@ -118,7 +130,7 @@ do_stop(){
     fi
 }
 
-do_restart(){
+do_restart() {
     do_stop
     sleep 0.5
     do_start
